namespace: spring-petclinic

images:
  genaiService:
    repository: tienminhktvn2
    name: spring-petclinic-genai-service
    tag: latest
  adminServer:
    repository: tienminhktvn2
    name: spring-petclinic-admin-server
    tag: latest
  customersService:
    repository: tienminhktvn2
    name: spring-petclinic-customers-service
    tag: latest
  vetsService:
    repository: tienminhktvn2
    name: spring-petclinic-vets-service
    tag: latest
  visitsService:
    repository: tienminhktvn2
    name: spring-petclinic-visits-service
    tag: latest
  apiGateway: 
    repository: tienminhktvn2
    name: spring-petclinic-api-gateway
    tag: latest
  discoveryServer:
    repository: tienminhktvn2
    name: spring-petclinic-discovery-server
    tag: latest
  configServer: 
    repository: tienminhktvn2
    name: spring-petclinic-config-server
    tag: latest

config:
  genaiService:
    uri: http://spring-petclinic-genai-service-service:8084
  customersService:
    uri: http://spring-petclinic-customers-service-service:8081
  vetsService:
    uri: http://spring-petclinic-vets-service-service:8083
  visitsService:
    uri: http://spring-petclinic-visits-service-service:8082
  discoveryServer:
    url: http://spring-petclinic-discovery-server-service:8761
  configServer: 
    url: http://spring-petclinic-config-server-service:8888
  tracingServer:
    url: http://spring-petclinic-tracing-server-service:9411/api/v2/spans