apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-server-deployment
  labels:
    app: admin-server-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin-server-pod
  template:
    metadata:
      name: admin-server-pod
      labels:
        app: admin-server-pod
    spec:
      initContainers:
        - name: wait-for-config-server
          image: darthcabs/tiny-tools:1
          args:
            - /bin/bash
            - -c
            - >
              set -x;
              while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' {{ .Values.config.configServer.url }})" != "200" ]]; do
                echo '.'
                sleep 15;
              done
        - name: wait-for-discovery-server
          image: darthcabs/tiny-tools:1
          args:
            - /bin/bash
            - -c
            - >
              set -x;
              while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' {{ .Values.config.discoveryServer.url }})" != "200" ]]; do
                echo '.'
                sleep 15;
              done
      containers:
        - name: admin-server-pod
          image: "{{ .Values.images.adminServer.repository }}/{{ .Values.images.adminServer.name }}:{{ .Values.images.adminServer.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9090
          env:
            - name: CONFIG_SERVER_URL
              value: "{{ .Values.config.configServer.url }}"
---
apiVersion: v1
kind: Service
metadata:
  name: admin-server
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: admin-server-pod
  ports:
    - name: admin-server-port
      protocol: TCP
      port: 9090
      targetPort: 9090
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  name: spring-petclinic.{{ .Values.namespace }}.admin-server.com
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: spring-petclinic.{{ .Values.namespace }}.admin-server.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: admin-server
                port:
                  number: 9090
