apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-api-gateway-deployment
  labels:
    app: spring-petclinic-api-gateway-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic-api-gateway-pod
  template:
    metadata:
      name: spring-petclinic-api-gateway-pod
      labels:
        app: spring-petclinic-api-gateway-pod
    spec:
      initContainers:
        - name: wait-for-config-server
          image: darthcabs/tiny-tools:1
          args:
            - /bin/bash
            - -c
            - >
              set -x;
              while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' {{ .Values.configServer.url }})" != "200" ]]; do
                echo '.'
                sleep 15;
              done
        - name: wait-for-discovery-server
          image: darthcabs/tiny-tools:1
          args:
            - /bin/bash
            - -c
            - >
              set -x;
              while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' {{ .Values.discoveryServer.url }})" != "200" ]]; do
                echo '.'
                sleep 15;
              done
      containers:
        - name: spring-petclinic-api-gateway-pod
          image: "{{ .Values.images.apiGateway.repository }}/{{ .Values.images.apiGateway.name }}:{{ .Values.images.apiGateway.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_SERVER_URL
              value: "{{ .Values.configServer.url }}"
            - name: DISCOVERY_SERVER_URL
              value: "{{ .Values.discoveryServer.url }}/eureka/"
            - name: TRACING_SERVER_URL
              value: "{{ .Values.tracingServer.url }}"
            - name: VETS_SERVICE_URI
              value: "{{ .Values.vetsService.uri }}"
            - name: VISITS_SERVICE_URI
              value: "{{ .Values.visitsService.uri }}"
            - name: CUSTOMERS_SERVICE_URI
              value: "{{ .Values.customersService.uri }}"
            - name: GENAI_SERVICE_URI
              value: "{{ .Values.genaiService.uri }}"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-api-gateway-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: spring-petclinic-api-gateway-pod
  ports:
    - name: spring-petclinic-api-gateway-port
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  name: spring-petclinic.{{ .Values.namespace }}.api-gateway.com
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: spring-petclinic.{{ .Values.namespace }}.api-gateway.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-petclinic-api-gateway-service
                port:
                  number: 8080