apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    app: api-gateway-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway-pod
  template:
    metadata:
      name: api-gateway-pod
      labels:
        app: api-gateway-pod
    spec:
      initContainers:
        - name: wait-for-config-server
          image: darthcabs/tiny-tools:1
          args:
            - /bin/bash
            - -c
            - >
              set -x;
              while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' {{ .Values.config.configServer.url }})" != "200" ]]; do
                echo '.'
                sleep 15;
              done
        - name: wait-for-discovery-server
          image: darthcabs/tiny-tools:1
          args:
            - /bin/bash
            - -c
            - >
              set -x;
              while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' {{ .Values.config.discoveryServer.url }})" != "200" ]]; do
                echo '.'
                sleep 15;
              done
      containers:
        - name: api-gateway-pod
          image: "{{ .Values.images.apiGateway.repository }}/{{ .Values.images.apiGateway.name }}:{{ .Values.images.apiGateway.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: CONFIG_SERVER_URL
              value: "{{ .Values.config.configServer.url }}"
---
apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: api-gateway-pod
  ports:
    - name: api-gateway-port
      protocol: TCP
      port: 8080
      targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  name: spring-petclinic.{{ .Values.namespace }}.api-gateway.com
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: spring-petclinic.{{ .Values.namespace }}.api-gateway.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: api-gateway
                port:
                  number: 8080