apiVersion: apps/v1
kind: Deployment
metadata:
  name: customers-service-deployment
  labels:
    app: customers-service-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customers-service-pod
  template:
    metadata:
      name: customers-service-pod
      labels:
        app: customers-service-pod
    spec:
      initContainers:
        - name: wait-for-config-server
          image: darthcabs/tiny-tools:1
          args:
            - /bin/bash
            - -c
            - >
              set -x;
              while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' {{ .Values.config.configServer.url }})" != "200" ]]; do
                echo '.'
                sleep 15;
              done
        - name: wait-for-discovery-server
          image: darthcabs/tiny-tools:1
          args:
            - /bin/bash
            - -c
            - >
              set -x;
              while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' {{ .Values.config.discoveryServer.url }})" != "200" ]]; do
                echo '.'
                sleep 15;
              done
      containers:
        - name: customers-service-pod
          image: "{{ .Values.images.customersService.repository }}/{{ .Values.images.customersService.name }}:{{ .Values.images.customersService.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
          env:
            - name: CONFIG_SERVER_URL
              value: "{{ .Values.config.configServer.url }}"
---
apiVersion: v1
kind: Service
metadata:
  name: customers-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: customers-service-pod
  ports:
    - name: customers-service-port
      protocol: TCP
      port: 8081
      targetPort: 8081
