apiVersion: apps/v1
kind: Deployment
metadata:
  name: genai-service-deployment
  labels:
    app: genai-service-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genai-service-pod
  template:
    metadata:
      name: genai-service-pod
      labels:
        app: genai-service-pod
    spec:
      initContainers:
        - name: wait-for-config-server
          image: darthcabs/tiny-tools:1
          args:
            - /bin/bash
            - -c
            - >
              set -x;
              while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' {{ .Values.config.configServer.url }})" != "200" ]]; do
                echo '.'
                sleep 15;
              done
        - name: wait-for-discovery-server
          image: darthcabs/tiny-tools:1
          args:
            - /bin/bash
            - -c
            - >
              set -x;
              while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' {{ .Values.config.discoveryServer.url }})" != "200" ]]; do
                echo '.'
                sleep 15;
              done
      containers:
        - name: genai-service-pod
          image: "{{ .Values.images.genaiService.repository }}/{{ .Values.images.genaiService.name }}:{{ .Values.images.genaiService.tag }}"
          imagePullPolicy: IfNotPresent
          env:
            - name: OPENAI_API_KEY
              value: "None"
            - name: AZURE_OPENAI_KEY
              value: "None"
            - name: AZURE_OPENAI_ENDPOINT
              value: "None"
            - name: CONFIG_SERVER_URL
              value: "{{ .Values.config.configServer.url }}"
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: genai-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: genai-service-pod
  ports:
    - name: genai-service-port
      protocol: TCP
      port: 8084
      targetPort: 8084
