apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.hostname.grafanaServer.name }}
  labels:
    app: {{ .Values.hostname.grafanaServer.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.hostname.grafanaServer.name }}
  template:
    metadata:
      name: {{ .Values.hostname.grafanaServer.name }}
      labels:
        app: {{ .Values.hostname.grafanaServer.name }}
    spec:
      containers:
        - name: {{ .Values.hostname.grafanaServer.name }}
          image: "{{ .Values.images.grafanaServer.repository }}:{{ .Values.images.grafanaServer.tag }}"
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.hostname.grafanaServer.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.hostname.grafanaServer.name }}
  ports:
    - name: {{ .Values.hostname.grafanaServer.name }}-port
      protocol: TCP
      port: 3030
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  name: spring-petclinic.{{ .Values.namespace }}.{{ .Values.hostname.tracingServer.name }}.com
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: spring-petclinic.{{ .Values.namespace }}.{{ .Values.hostname.grafanaServer.name }}.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.hostname.grafanaServer.name }}
                port:
                  number: 3030