apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-tracing-server-deployment
  labels:
    app: spring-petclinic-tracing-server-deployment
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic-tracing-server-pod
  template:
    metadata:
      name: spring-petclinic-tracing-server-pod
      labels:
        app: spring-petclinic-tracing-server-pod
    spec:
      initContainers:
        - name: wait-for-config-server
          image: darthcabs/tiny-tools:1
          args:
            - /bin/bash
            - -c
            - >
              set -x;
              while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://spring-petclinic-config-server-service:8888)" != "200" ]]; do
                echo '.'
                sleep 15;
              done
        - name: wait-for-discovery-server
          image: darthcabs/tiny-tools:1
          args:
            - /bin/bash
            - -c
            - >
              set -x;
              while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://spring-petclinic-discovery-server-service:8761)" != "200" ]]; do
                echo '.'
                sleep 15;
              done
      containers:
        - name: spring-petclinic-tracing-server-pod
          image: openzipkin/zipkin
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9411
          env:
            - name: CONFIG_SERVER_URL
              value: "http://spring-petclinic-config-server-service:8888"
            - name: DISCOVERY_SERVER_URL
              value: "http://spring-petclinic-discovery-server-service:8761/eureka/"
---
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-tracing-server-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: spring-petclinic-tracing-server-pod
  ports:
    - name: spring-petclinic-tracing-server-port
      protocol: TCP
      port: 9411
      targetPort: 9411
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations: {}
  name: spring-petclinic.tracing-server.com
  namespace: {{ .Values.namespace }}
spec:
  ingressClassName: nginx
  rules:
    - host: spring-petclinic.tracing-server.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: spring-petclinic-tracing-server-service
                port:
                  number: 9411
